# Generated by Django 4.1.5 on 2023-02-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprofile", "0002_sprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprofile",
            name="gre_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sprofile",
            name="ilets_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sprofile",
            name="lor",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sprofile",
            name="research_experience",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="sprofile",
            name="specialization",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
