# Generated by Django 4.1.5 on 2023-02-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0004_remove_sprofile_specialization_sprofile_toefl_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprofile',
            old_name='toefl_score',
            new_name='family_income',
        ),
        migrations.RemoveField(
            model_name='sprofile',
            name='career_goals',
        ),
        migrations.RemoveField(
            model_name='sprofile',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='sprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='sprofile',
            name='scholarship',
        ),
        migrations.AlterField(
            model_name='sprofile',
            name='internships',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sprofile',
            name='work_experience',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
