# Generated by Django 4.1.5 on 2023-02-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0006_activity_remove_sprofile_activities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='activities',
        ),
    ]
