# Generated by Django 4.1.5 on 2023-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0007_rename_name_activity_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprofile',
            name='activities',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='sprofile',
            name='activities',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
