# Generated by Django 4.1.5 on 2023-02-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0008_remove_sprofile_activities_delete_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprofile',
            name='activities',
            field=models.CharField(blank=True, choices=[('music', 'Music'), ('sports', 'Sports'), ('dance', 'Dance')], default=None, max_length=6, null=True),
        ),
    ]
