# Generated by Django 4.1.5 on 2023-02-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0009_alter_sprofile_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprofile',
            name='activities',
        ),
        migrations.AddField(
            model_name='sprofile',
            name='speak_french',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sprofile',
            name='sports',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
