# Generated by Django 4.1.5 on 2023-02-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0010_remove_sprofile_activities_sprofile_speak_french_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprofile',
            name='gender',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
