# Generated by Django 4.1.5 on 2023-02-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0012_alter_sprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprofile',
            name='gender',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
