# Generated by Django 4.1.5 on 2023-02-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprofile', '0013_alter_sprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprofile',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
