# Generated by Django 4.1.5 on 2023-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprofile", "0014_alter_sprofile_gender"),
    ]

    operations = [
        migrations.RemoveField(model_name="sprofile", name="email",),
        migrations.AddField(
            model_name="sprofile",
            name="gate_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
